# This workflow will run Terraform init, validate, and plan on Pull Request=
name: Template E2E test
on:
  pull_request_target:
  issue_comment:
    types: [created]
  workflow_dispatch:

jobs:
  run_template_e2e_test:
    if: |
      ${{
        (github.event_name == 'issue_comment' && contains(github.event.comment.body, '/run-e2e-test' ))
        || github.event_name == 'workflow_dispatch'
        }}
    runs-on: ubuntu-latest
    environment: e2e
    name: Template E2E tests
    steps:

    - name: Check out repository with main branch
      uses: actions/checkout@v3
      if: ${{ github.event_name == 'workflow_dispatch' }}

    - name: PRINT SHA
      run: echo  ${{ github.event.pull_request.head.sha }}

    - name: Check out repository with Pull Request HEAD
      uses: actions/checkout@v3
      #if: ${{ github.event_name == 'issue_comment' && contains(github.event.comment.body, '/run-e2e-test') }}
      with:
        ref: ${{ github.event.pull_request.head.sha }}
      

    - name: Run e2e test script
      run: |
        bash e2e/template_e2e_tests/run_e2e_test.sh

