name: Workflow Run Workflow

on:
  workflow_run:
    workflows: ["Pull Request Workflow"]
    types:
      - completed

jobs:
  retrieve-artifacts:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download artifact from pull_request workflow
        uses: actions/download-artifact@v3
        with:
          name: build-output

      - name: Show artifact content
        run: |
          cat build_output.txt
